configMapGenerator:
- name: env-injector-files
  namespace: llm-d-thibrahi
  files:
    - sitecustomize.py
    - profiler_config.yaml
    - metrics_observer.py
generatorOptions:
  disableNameSuffixHash: true
